# Header
menu:                      # Links in the navigation bar
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: false                  # Display banner
  url:                           # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 250                         # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar: /profile_photo.jpg       # Path to the avatar image relative to /source
author: NY Jan
subtitle: a college student studying cs
links:
  - name: Bluesky
    icon: fa-brands fa-bluesky      # Find icon codes at https://fontawesome.com/search
    url: https://bsky.app/profile/nnyjan02426.bsky.social
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/nnyjan02426
  - name: Github Page
    icon: fa-solid fa-earth-asia
    url: https://nnyjan02426.github.io

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
#      - archive
#      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: true          # Enable Valine comment system
    appId: dPxsABf1n5paggSR55jkPt6i-MdYXbMMI
    appKey: DKXHLgI4fMj3f1vJKnvFxOu0
    placeholder: Feel free to say anything!
    pageSize: 10
    highlight: true
    serverURLs: 
    lang: en
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo
  waline:
    enable: false          # Enable Waline comment system
    serverURL: 

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
